### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by JamieSlome** [Citi/citi-ospo#3]
Provide a high level overview of the contents and the purpose of the repository 👍

**Comment by msagi** [comment]
Apologies, if I'm jumping the gun here 😄 . @JamieSlome do you accept external personal contributions?

**Comment by JamieSlome** [comment]
@msagi absolutely!

**Comment by msagi** [comment]
@JamieSlome I'd be honoured to work on this issue (as external personal contributor) 😄

**Comment by JamieSlome** [comment]
@msagi, feel free to fork the project and submit a PR when you're ready! ❤️

**Comment by KatWarr** [comment]
Hi @msagi , it's great that you'd like to contribute to the project! Although, I had already started working on this before I saw this discussion. I've created a new [pull request](https://github.com/Citi/citi-ospo/pull/6) for it. I'd really appreciate if you could take a look and provide any feedback for improvements.

**Comment by JamieSlome** [comment]
As mentioned in the other PR, there are some nice templates that we can use, such as [this one](https://github.com/othneildrew/Best-README-Template#readme-top).
